<div style="text-align:center; font-weight: bold; font-size: 25px; font-family: 'Times New Roman', Times, serif;"><span style="border-bottom: 3px double black;">Assignment V</span></div><br>

<span style="font-family: 'Times New Roman'; font-weight: bold; font-size: 20px;">
1. You are given a 4x4 matrix named P as follows:
</span><br><br>

$$
P = \begin{bmatrix}
3 & -8 & 10 & 5 \\
9 & 7 & 12 & 30 \\
54 & 0 & 6 & -13 \\
1 & 78 & 2 & 25 \\
\end{bmatrix}
$$
<br>
<span style="font-family: 'Times New Roman'; font-size: 18px;">
(a) Print out the elements which are greater than 9 using “where” method in Numpy module.
</span>

In [1]:
import numpy as np

# Given 4x4 matrix P
P = np.array([[3, -8, 10, 5],
              [9, 7, 12, 30],
              [54, 0, 6, -13],
              [1, 78, 2, 25]])

# Print elements greater than 9 using "where" method
result = np.where(P > 9)
print("Elements greater than 9:")
for i in range(len(result[0])):
    print(f"Element at position ({result[0][i]}, {result[1][i]}): {P[result[0][i], result[1][i]]}")

Elements greater than 9:
Element at position (0, 2): 10
Element at position (1, 2): 12
Element at position (1, 3): 30
Element at position (2, 0): 54
Element at position (3, 1): 78
Element at position (3, 3): 25


<hr style = "border: 0.5px solid black;">

<span style="font-family: 'Times New Roman'; font-weight: bold; font-size: 20px;">
2. You are given a 3 Dimensional matrix named A as follows:
</span><br><br>

$$
A = \begin{bmatrix}
\begin{bmatrix}
0 & \color{red}{-23} & \color{red}{4} & 67 \\
3 & \color{red}{5} & \color{red}{9} & 1 \\
7 & \color{red}{3} & \color{red}{-12} & 4 \\
3 & \color{red}{0} & \color{red}{-6} & 1 \\
9 & \color{red}{7} & \color{red}{6} & 4 \\
\end{bmatrix} \\
\begin{bmatrix}
5 & 3 & 0 & -9 \\
2 & 8 & 7 & 13 \\
-7 & 14 & 8 & 4 \\
\color{blue}{19} & \color{blue}{-5} & \color{blue}{35} & \color{blue}{-18} \\
\color{blue}{16} & \color{blue}{23} & \color{blue}{90} & \color{blue}{1} \\
\end{bmatrix} \\
\begin{bmatrix}
10 & 20 & 62 & 34 \\
-45 & 13 & 42 & 32 \\
33 & 76 & 39 & 22 \\
\color{blue}{78} & \color{blue}{46} & \color{blue}{12} & \color{blue}{18} \\
\color{blue}{55} & \color{blue}{26} & \color{blue}{68} & \color{blue}{45} \\
\end{bmatrix}
\end{bmatrix}
$$
<br>
<span style="font-family: 'Times New Roman'; font-size: 18px;">
&nbsp;&nbsp;&nbsp;(a) Provide a Python script to construct a given 3 Dimensional A matrix.
</span><br>
<span style="font-family: 'Times New Roman'; font-size: 18px;">
&nbsp;&nbsp;&nbsp;(b) Write a program to create a matrix named B for the elements in the red block of given matrix A.
</span><br>
<span style="font-family: 'Times New Roman'; font-size: 18px;">
&nbsp;&nbsp;&nbsp;(c) Write a program to create a matrix named C for the elements in the blue block of given matrix A.
</span>

In [4]:
import numpy as np

# Function to construct the given 3-dimensional matrix A using NumPy
def construct_matrix():
    A = np.array([
        [
            np.array([0, -23, 4, 67, 3, 5, 9, 1, 7, 3, -12, 4, 3, 0, -6, 1, 9, 7, 6, 4]).reshape(5, 4),
            np.array([5, 3, 0, -9, 2, 8, 7, 13, -7, 14, 8, 4, 19, -5, 35, -18, 16, 23, 90, 1]).reshape(5, 4),
            np.array([10, 20, 62, 34, -45, 13, 42, 32, 33, 76, 39, 22, 78, 46, 12, 18, 55, 26, 68, 45]).reshape(5, 4),
        ]
    ])
    return A

# Function to create a new matrix B for the elements in the red block of given matrix A.
def create_matrix_B(matrix_A):
    B = matrix_A[:, 0, :, 1:3]
    return B

# Function to create a new matrix C for the elements in the blue block of given matrix A.
def create_matrix_C(matrix_A):
    C = matrix_A[:, 1:, 3:5, :]
    return C


matrix_A = construct_matrix()
matrix_B = create_matrix_B(matrix_A)
matrix_C = create_matrix_C(matrix_A)

# Display the matrices
print("Matrix A:")
print(matrix_A)

print("\nMatrix B:")
print(matrix_B)

print("\nMatrix C:")
print(matrix_C)

Matrix A:
[[[[  0 -23   4  67]
   [  3   5   9   1]
   [  7   3 -12   4]
   [  3   0  -6   1]
   [  9   7   6   4]]

  [[  5   3   0  -9]
   [  2   8   7  13]
   [ -7  14   8   4]
   [ 19  -5  35 -18]
   [ 16  23  90   1]]

  [[ 10  20  62  34]
   [-45  13  42  32]
   [ 33  76  39  22]
   [ 78  46  12  18]
   [ 55  26  68  45]]]]

Matrix B:
[[[-23   4]
  [  5   9]
  [  3 -12]
  [  0  -6]
  [  7   6]]]

Matrix C:
[[[[ 19  -5  35 -18]
   [ 16  23  90   1]]

  [[ 78  46  12  18]
   [ 55  26  68  45]]]]


<hr style = "border: 0.5px solid black;">

<span style="font-family: 'Times New Roman'; font-weight: bold; font-size: 20px;">
3. (a) Generate a 3D Numpy array of matrix shape (2,4,4) with random integers between 0 and 50. <br><br>
(b) Create a Python program to print out the Diagonal Toeplitz Matrix.
</span><br><br>

<span style="font-family: 'Times New Roman'; font-size: 18px;">
The output matrix is:
</span><br>

$$
\begin{bmatrix}
13 & 20 & 0 & 0 & 0 & 0 \\
5 & 13 & 20 & 0 & 0 & 0 \\
0 & 5 & 13 & 20 & 0 & 0 \\
0 & 0 & 5 & 13 & 20 & 0 \\
0 & 0 & 0 & 5 & 13 & 20 \\
0 & 0 & 0 & 0 & 5 & 13 \\
\end{bmatrix}
$$


In [10]:
import numpy as np

# (a) Generate a 3D Numpy array of matrix shape (2, 4, 4) with random integers between 0 and 50
random_array = np.random.randint(0, 51, size=(2, 4, 4))

# Display the generated 3D Numpy array
print("Generated 3D Numpy array:")
print(random_array)

# (b) Create a Python program to print out the Diagonal Toeplitz Matrix
diagonal_toeplitz_matrix = np.zeros_like(random_array)

for i in range(random_array.shape[0]):
    for j in range(random_array.shape[1]):
        diagonal_toeplitz_matrix[i, j, :] = np.concatenate(
            [random_array[i, j, :], np.zeros(random_array.shape[2] - 4)])

# Display the Diagonal Toeplitz Matrix
print("\nDiagonal Toeplitz Matrix:")
print(diagonal_toeplitz_matrix)


Generated 3D Numpy array:
[[[25  4  8 29]
  [43 15 49 21]
  [28  2 43 19]
  [11 28  0 23]]

 [[36  3 39 14]
  [ 1 16 27  3]
  [40 13 35 27]
  [27 14 25 13]]]

Diagonal Toeplitz Matrix:
[[[25  4  8 29]
  [43 15 49 21]
  [28  2 43 19]
  [11 28  0 23]]

 [[36  3 39 14]
  [ 1 16 27  3]
  [40 13 35 27]
  [27 14 25 13]]]


<hr style = "border: 0.5px solid black;">

<span style="font-family: 'Times New Roman'; font-weight: bold; font-size: 20px;">
4. You are given a 4 x 4 matrix and represent as a Numpy array in Python.
</span><br><br>

$$
M = \begin{bmatrix}
8 & 4 & -5 & 10 \\
0 & 12 & 9 & -3 \\
6 & 32 & 2 & 1 \\
5 & 7 & 3 & 11 \\
\end{bmatrix}
$$
<br>

<span style="font-family: 'Times New Roman'; font-size: 18px;">
&nbsp;&nbsp;&nbsp;(a) Print out the index of elements in column major of the given matrix using argsort function in Numpy module.
</span><br>
<span style="font-family: 'Times New Roman'; font-size: 18px;">
&nbsp;&nbsp;&nbsp;(b) Concatenate the matrix N to the given matrix M along the appropriate axis to form a new matrix.
</span><br>

$$
N = \begin{bmatrix}
2 & -5 \\
8 & 23 \\
34 & 0 \\
-1 & 6 \\
\end{bmatrix}
$$



In [11]:
import numpy as np

# Given 4x4 matrix M
M = np.array([[8, 4, -5, 10],
              [0, 12, 9, -3],
              [6, 32, 2, 1],
              [5, 7, 3, 11]])

# (a) Print out the index of elements in column major using argsort
column_major_indices = np.argsort(M, axis=None)

# Display the column major indices
print("Column Major Indices:")
print(column_major_indices)

# (b) Concatenate matrix N to matrix M along the appropriate axis
N = np.array([[2, -5],
              [8, 23],
              [34, 0],
              [-1, 6]])

# Concatenate matrices M and N along axis 1 (columns) to form a new matrix
new_matrix = np.concatenate((M, N), axis=1)

# Display the new matrix
print("\nNew Matrix (Concatenated along columns):")
print(new_matrix)

Column Major Indices:
[ 2  7  4 11 10 14  1 12  8 13  0  6  3 15  5  9]

New Matrix (Concatenated along columns):
[[ 8  4 -5 10  2 -5]
 [ 0 12  9 -3  8 23]
 [ 6 32  2  1 34  0]
 [ 5  7  3 11 -1  6]]


<hr style = "border: 0.5px solid black;">

<span style="font-family: 'Times New Roman'; font-weight: bold; font-size: 20px;">
5. Write a Python program that calculates and prints the following values for the number 25, each rounded to three decimal places:
</span><br><br>

<span style="font-family: 'Times New Roman'; font-size: 18px;">
&nbsp;&nbsp;&nbsp;(a) The base-10 logarithm (log<sub>10</sub>) of 25.
</span><br>
<span style="font-family: 'Times New Roman'; font-size: 18px;">
&nbsp;&nbsp;&nbsp;(b) The exponential function (exp) of 25.
</span>

In [12]:
import math

# Given number in question
number = 25

# (a) Calculate and print the base-10 logarithm (log10) of 25
log10_result = round(math.log10(number), 3)
print(f"The base-10 logarithm (log10) of {number} is: {log10_result}")

# (b) Calculate and print the exponential function (exp) of 25
exp_result = round(math.exp(number), 3)
print(f"The exponential function (exp) of {number} is: {exp_result}")

The base-10 logarithm (log10) of 25 is: 1.398
The exponential function (exp) of 25 is: 72004899337.386


<hr style = "border: 0.5px solid black;">